### ISSUE TITLE
sticky consumer: how to grab a consumer by its groupId

### ISSUE THREAD

**Issue by adam-thibodeaux** [Saamsa/SourceSystemApp#21]
need to create a method for killing all consumers on key=kill message
one consumer 'sticks' to the topic, new consumers don't displace 
**how do we grab a consumer by its groupId?**

**Comment by shamilahfaria** [comment]
old consumer is attached to topic and being read
new consumer can't be attached to topic because old consumer is on it.
but info is still being sent to aws ? regardless of which consumer it is? so it doesn't matter for functional purposes, just testing purposes.
